# fly.toml app configuration file generated for app-bitter-frog-4443 on 2024-10-11T20:54:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app-bitter-frog-4443'
primary_region = 'iad'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web']

[processes]
  web = "chainlit run app.py -h 0.0.0.0 -p 8080"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
